/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utils.koneksi;

/**
 *
 * @author Mahardicka
 */
public class home extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    String idKar;
    barang barangPage = new barang();
    kasir kasirPage = new kasir();
    karyawan karyawanPage = new karyawan();
    vendor vendorPage = new vendor();
//    member memberPage = new member();
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    void setupDB(){
         // db
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }   
    
    public void onLoad(String id){
       idKar = id;
       sql = "SELECT nama,role,email FROM karyawan WHERE id='"+id+"'";
       setupDB();
        try {
            rs = stat.executeQuery(sql);
            if(rs.next()){          
                namaKar.setText(rs.getString("nama"));
                idKaryawan.setText(id);
                emailKar.setText(rs.getString("email"));
                roleKar.setText(rs.getString("role"));
            } else {
                JOptionPane.showMessageDialog(null,"error database get profile.");
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "error "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btkasir = new javax.swing.JButton();
        btbarang = new javax.swing.JButton();
        btmember = new javax.swing.JButton();
        btadmin = new javax.swing.JButton();
        btvendor = new javax.swing.JButton();
        btlaporan = new javax.swing.JButton();
        btpegawai = new javax.swing.JButton();
        namaKar = new javax.swing.JLabel();
        emailKar = new javax.swing.JLabel();
        roleKar = new javax.swing.JLabel();
        idKaryawan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btkasir.setText("KASIR");
        btkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkasirActionPerformed(evt);
            }
        });
        getContentPane().add(btkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 84, 94, 70));

        btbarang.setText("BARANG");
        btbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 84, 94, 70));

        btmember.setText("MEMBER");
        btmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 84, 94, 70));

        btadmin.setText("ADMIN");
        btadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadminActionPerformed(evt);
            }
        });
        getContentPane().add(btadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 172, 94, 70));

        btvendor.setText("VENDOR");
        btvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvendorActionPerformed(evt);
            }
        });
        getContentPane().add(btvendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 172, 94, 70));

        btlaporan.setText("LAPORAN");
        btlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 172, 94, 70));

        btpegawai.setText("PEGAWAI");
        btpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 260, 94, 70));

        namaKar.setText("nama karyawan");
        getContentPane().add(namaKar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        emailKar.setText("email karyawan");
        getContentPane().add(emailKar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        roleKar.setText("role karyawan");
        getContentPane().add(roleKar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        idKaryawan.setText("id karyawan");
        getContentPane().add(idKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkasirActionPerformed
        // TODO add your handling code here:
        kasirPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btkasirActionPerformed

    private void btbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbarangActionPerformed
        // TODO add your handling code here:
        barangPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btbarangActionPerformed

    private void btmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmemberActionPerformed
        // TODO add your handling code here:
        // memberPage.setVisible(true);
    }//GEN-LAST:event_btmemberActionPerformed

    private void btadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btadminActionPerformed

    private void btvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvendorActionPerformed
        // TODO add your handling code here:
        vendorPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btvendorActionPerformed

    private void btlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlaporanActionPerformed

    private void btpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpegawaiActionPerformed
        // TODO add your handling code here:
        karyawanPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btpegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadmin;
    private javax.swing.JButton btbarang;
    private javax.swing.JButton btkasir;
    private javax.swing.JButton btlaporan;
    private javax.swing.JButton btmember;
    private javax.swing.JButton btpegawai;
    private javax.swing.JButton btvendor;
    private javax.swing.JLabel emailKar;
    private javax.swing.JLabel idKaryawan;
    private javax.swing.JLabel namaKar;
    private javax.swing.JLabel roleKar;
    // End of variables declaration//GEN-END:variables
}
